import React from 'react'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const layout = ({children}) => {
  return (
    <div>{children}</div>
  )
}

export default layout